[package]
name = "cuprate-peer"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Boog900"]


[dependencies]
cuprate-protocol = {path="../protocol"}
cuprate-common = {path = "../../common"}
monero-wire = {path= "../../net/monero-wire"}
monero = {git="https://github.com/Boog900/monero-rs.git", branch="db", features=["database"]}
tower = {version = "0.4.13", features = ["util", "discover"]}
futures = "0.3.26"
thiserror = "1.0.39"
