[package]
name        = "cuprate-constants"
version     = "0.0.0"
edition     = "2021"
description = "Constant/static data used throughout Cuprate"
license     = "MIT"
authors     = ["hinto-janai"]
repository  = "https://github.com/Cuprate/cuprate/tree/main/constants"
keywords    = ["cuprate", "constants"]

[features]
default      = ["monero-serai"]
monero-serai = ["dep:monero-serai"]

[dependencies]
monero-serai = { workspace = true, optional = true }

[dev-dependencies]
monero-serai      = { workspace = true }
hex               = { workspace = true, features = ["std"] }
pretty_assertions = { workspace = true }

[lints]
workspace = true