[package]
name        = "cuprate-types"
version     = "0.0.0"
edition     = "2021"
description = "Cuprate data types"
license     = "MIT"
authors     = ["hinto-janai"]
repository  = "https://github.com/Cuprate/cuprate/tree/main/types"
keywords    = ["cuprate", "types"]

[features]
default    = ["blockchain", "epee", "serde", "json"]
blockchain = ["dep:indexmap", "dep:cuprate-helper", "cuprate-helper/crypto", "rpc"]
epee       = ["dep:cuprate-epee-encoding"]
serde      = ["dep:serde"]
proptest   = ["dep:proptest",  "dep:proptest-derive"]
json       = ["dep:cuprate-hex", "dep:cuprate-helper"]
rpc        = ["dep:cuprate-hex", "json"]

[dependencies]
cuprate-epee-encoding = { workspace = true, optional = true, features = ["std"] }
cuprate-helper        = { workspace = true, optional = true, features = ["cast"] }
cuprate-fixed-bytes   = { workspace = true, features = ["std", "serde"] }
cuprate-hex           = { workspace = true, optional = true }

bitflags         = { workspace = true }
bytes            = { workspace = true }
cfg-if           = { workspace = true }
curve25519-dalek = { workspace = true }
monero-serai     = { workspace = true }
serde            = { workspace = true, features = ["std", "derive"], optional = true }
strum            = { workspace = true, features = ["derive"] }
thiserror        = { workspace = true }
indexmap         = { workspace = true, features = ["std"], optional = true }

proptest = { workspace = true, optional = true }
proptest-derive  = { workspace = true, optional = true }

[dev-dependencies]
hex-literal       = { workspace = true }
pretty_assertions = { workspace = true }
serde_json        = { workspace = true, features = ["std"] }

[lints]
workspace = true
