# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs.
cache = false

# Verbose program output
# Accepts log level: "error", "warn", "info", "debug", "trace"
verbose = "debug"

# Don't show interactive progress bar while checking links.
no_progress = true

# Exclude URLs and mail addresses from checking (supports regex).
exclude = ["file://"]

# Exclude these filesystem paths from getting checked.
exclude_path = [
    # Contains local link meant for `lib.rs`.
    "storage/blockchain/README.md",
    # Contains local link.
    "books/protocol/src/consensus_rules/transactions/outputs.md",
]

# Exclude all private IPs from checking.
# Equivalent to setting `exclude_private`, `exclude_link_local`, and
# `exclude_loopback` to true.
exclude_all_private = true