[package]
name = "cuprate-bucket-set"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["SyntheticBird"]

[dependencies]
arrayvec = { workspace = true }
rand     = { workspace = true, features = ["std", "std_rng"]}

cuprate-p2p-core = { workspace = true }

[lints]
workspace = true
