[package]
name = "cuprate-p2p-bucket"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["SyntheticBird"]

[dependencies]
arrayvec = { workspace = true }
rand     = { workspace = true, features = ["std", "std_rng"]}

[lints]
workspace = true
