[package]
name        = "cuprate-criterion-database"
version     = "0.0.0"
edition     = "2021"
description = "Criterion benchmarking for cuprate-database"
license     = "MIT"
authors     = ["hinto-janai"]
repository  = "https://github.com/Cuprate/cuprate/tree/main/benches/criterion/cuprate-database"
keywords    = ["cuprate", "database", "benchmark"]

[features]
default = ["heed"]
heed    = ["cuprate-database/heed", "cuprate-blockchain/heed"]
redb    = ["cuprate-database/redb", "cuprate-blockchain/redb"]

[dependencies]
criterion          = { workspace = true }
cuprate-database   = { path = "../../../storage/database" }
cuprate-blockchain = { path = "../../../storage/blockchain" }
cuprate-helper     = { path = "../../../helper", features = ["fs", "thread"] }

function_name = { workspace = true }
tempfile      = { workspace = true}

[[bench]]
name    = "main"
harness = false

[lints]
workspace = true