[package]
name        = "cuprate-criterion-example"
version     = "0.0.0"
edition     = "2021"
description = "Criterion benchmarking example for Cuprate"
license     = "MIT"
authors     = ["hinto-janai"]
repository  = "https://github.com/Cuprate/cuprate/tree/main/benches/criterion/example"
keywords    = ["cuprate", "criterion", "benchmark", "example"]

[dependencies]
criterion     = { workspace = true }
function_name = { workspace = true }
serde_json    = { workspace = true, features = ["default"] }

[[bench]]
name    = "main"
harness = false

[lints]
workspace = true