[package]
name = "cuprate-async-buffer"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Boog900"]

[dependencies]
thiserror = { workspace = true }
futures = { workspace = true, features = ["std"] }
pin-project = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }