[package]
name = "cuprate-protocol"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Boog900"]


[dependencies]
monero-wire = {path= "../../net/monero-wire"}
monero = {git="https://github.com/Boog900/monero-rs.git", branch="db", features=["database"]}
thiserror = "1.0.39"
