[package]
name        = "cuprate-rpc-interface"
version     = "0.0.0"
edition     = "2021"
description = "Cuprate's RPC interface library"
license     = "MIT"
authors     = ["hinto-janai"]
repository  = "https://github.com/Cuprate/cuprate/tree/main/rpc/cuprate-rpc-interface"
keywords    = ["cuprate", "rpc", "interface"]

[features]

[dependencies]

[dev-dependencies]
