[package]
name        = "cuprate-harness-test"
version     = "0.0.0"
edition     = "2021"
description = "Test for Cuprate's benchmarking harness"
license     = "MIT"
authors     = ["hinto-janai"]
repository  = "https://github.com/Cuprate/cuprate/tree/main/benches/macro/harness-test"
keywords    = ["cuprate", "benchmarking", "harness", "test"]

[dependencies]
cuprate-harness-lib = { path = "../lib" }

[dev-dependencies]