[package]
name = "concurrent-map-builder"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Boog900"]

[dependencies]
indexmap = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
