[package]
name = "cuprate-zmq-types"
version = "0.1.0"
edition = "2021"
description = "Types for the ZMQ Pub/Sub API"
license = "MIT"
authors = ["dimalinux", "The Monero Project"]
repository = "https://github.com/Cuprate/cuprate/tree/main/zmq/types"

[dependencies]

[dev-dependencies]

[lints]
workspace = true

