//! TODO

/// TODO
pub const HF_VERSION_DYNAMIC_FEE: u64 = 4;

/// TODO
pub const HF_VERSION_MIN_MIXIN_4: u64 = 6;

/// TODO
pub const HF_VERSION_MIN_MIXIN_6: u64 = 7;

/// TODO
pub const HF_VERSION_MIN_MIXIN_10: u64 = 8;

/// TODO
pub const HF_VERSION_MIN_MIXIN_15: u64 = 15;

/// TODO
pub const HF_VERSION_ENFORCE_RCT: u64 = 6;

/// TODO
pub const HF_VERSION_PER_BYTE_FEE: u64 = 8;

/// TODO
pub const HF_VERSION_SMALLER_BP: u64 = 10;

/// TODO
pub const HF_VERSION_LONG_TERM_BLOCK_WEIGHT: u64 = 10;

/// TODO
pub const HF_VERSION_MIN_2_OUTPUTS: u64 = 12;

/// TODO
pub const HF_VERSION_MIN_V2_COINBASE_TX: u64 = 12;

/// TODO
pub const HF_VERSION_SAME_MIXIN: u64 = 12;

/// TODO
pub const HF_VERSION_REJECT_SIGS_IN_COINBASE: u64 = 12;

/// TODO
pub const HF_VERSION_ENFORCE_MIN_AGE: u64 = 12;

/// TODO
pub const HF_VERSION_EFFECTIVE_SHORT_TERM_MEDIAN_IN_PENALTY: u64 = 12;

/// TODO
pub const HF_VERSION_EXACT_COINBASE: u64 = 13;

/// TODO
pub const HF_VERSION_CLSAG: u64 = 13;

/// TODO
pub const HF_VERSION_DETERMINISTIC_UNLOCK_TIME: u64 = 13;

/// TODO
pub const HF_VERSION_BULLETPROOF_PLUS: u64 = 15;

/// TODO
pub const HF_VERSION_VIEW_TAGS: u64 = 15;

/// TODO
pub const HF_VERSION_2021_SCALING: u64 = 15;
