[package]
name = "cuprate-p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Boog900"]

[dependencies]
monero-wire = { path = "../../net/monero-wire" }
monero-p2p = { path = "../monero-p2p", features = ["borsh"] }
monero-address-book = { path = "../address-book" }
cuprate-helper = { path = "../../helper" }

tower = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
tokio-stream = { workspace = true, features = ["sync"] }
futures = { workspace = true, features = ["std"] }
pin-project = { workspace = true }

bytes = { workspace = true, features = ["std"] }
indexmap = { workspace = true, features = ["std"] }
rand = { workspace = true, features = ["std", "std_rng"] }
rand_distr = { workspace = true, features = ["std"] }
hex = { workspace = true, features = ["std"] }
tracing = { workspace = true, features = ["std", "attributes"] }

# REMOVE ME
tracing-subscriber = { version = "0.3.18" }

[dev-dependencies]
cuprate-test-utils = {path = "../../test-utils"}
tracing-subscriber = { version = "0.3.18" }

