name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Show colored output in CI.
  CARGO_TERM_COLOR: always
  # Show full panics.
  RUST_BACKTRACE: "full"
  # Increase thread stack size to 8 megabytes.
  RUST_MIN_STACK: 8000000
  # Fail on documentation warnings.
  RUSTDOCFLAGS: '-D warnings'
  # Enable debug information generation for build dependencies.
  CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG: true
  # Build commands.
  CMD_DOC: cargo doc --all-features --no-deps
  CMD_CLIPPY: cargo clippy --all-features --all-targets -- -D warnings
  CMD_TEST: cargo test --all-features
  CMD_BUILD: cargo build --all-features --all-targets
  CMD_HACK: |
    cargo install cargo-hack --locked
    cargo hack check --feature-powerset --no-dev-deps

jobs:
  # Run format separately.
  #
  # This will fast-cancel other CI early if this fails.
  #
  # `cargo fmt` checks _all_ code, regardless of the OS
  # or any `#[cfg]`'s, so this only needs to run on Linux.
  fmt:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: Format
        run: cargo fmt --all --check

  # Run typo checker separately.
  # This will fast-cancel other CI early if this fails.
  typo:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Spell Check
      uses: crate-ci/typos@master

  # Run 32-bit WASM support check separately.
  wasm-32-bit-support:
    runs-on: ubuntu-slim

    strategy:
      matrix:
        # The list of crates to check for WASM 32 bit support
        #  TODO: check features.
        crate: [
            cuprate-epee-encoding,
            cuprate-rpc-types,
            cuprate-fixed-bytes,
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Build WASM 32-bit
        run: cargo build --target wasm32-unknown-unknown --features __not_public_32_bit -p ${{ matrix.crate }}

  # CI, runs on GitHub provided OSs.
  ci:
    runs-on: ${{ matrix.os.runner }}

    strategy:
      matrix:
        os: [
            { runner: windows-2022, name: windows, architecture: x86_64 }, # EOL = 2026-10-13 | <https://endoflife.date/windows-server>
            { runner: macos-15, name: macos, architecture: aarch64 },      # EOL = 2027-09-16 | <https://endoflife.date/macos>
            { runner: ubuntu-24.04, name: linux, architecture: x86_64 },   # EOL = 2029-05-31 | <https://endoflife.date/ubuntu>
            { runner: ubuntu-24.04-arm, name: linux, architecture: aarch64 },
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ matrix.os.runner }}

      - name: Download monerod
        uses: ./.github/actions/monerod-download
        with:
          os: ${{ matrix.os.name }}
          arch: ${{ matrix.os.architecture }}

      - name: Install dependencies (Windows)
        if: matrix.os.runner == 'windows-2022'
        uses: lukka/get-cmake@v3.31.6 # Needed for `randomx-rs`

      - name: Documentation
        run: ${{ env.CMD_DOC }}

      - name: Clippy (fail on warnings)
        run: ${{ env.CMD_CLIPPY }}

      - name: Test
        run: ${{ env.CMD_TEST }}

      - name: Build
        run: ${{ env.CMD_BUILD }}

      - name: Hack Check
        run: ${{ env.CMD_HACK }}

  # CI, runs in a Docker image.
  ci-docker:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os.image }}

    strategy:
      matrix:
        os:
        - { image: alpine:latest, commands: "apk update && apk add alpine-sdk cmake curl bash monero && ln -sf /usr/bin/monerod monerod" } # Alpine is a special case due to its musl libc
        - { image: archlinux:latest, commands: "pacman -Syyu --noconfirm base-devel git cmake openssl" }
        - { image: debian:stable, commands: "apt update && apt -y install build-essential curl cmake git pkg-config libssl-dev" }
        - { image: fedora:latest, commands: "dnf install --assumeyes @development-tools gcc gcc-c++ cmake git openssl-devel perl-core" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ matrix.os.image }}

      - name: Dependencies
        run: ${{ matrix.os.commands }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Download monerod
        if: matrix.os.image != 'alpine:latest'
        uses: ./.github/actions/monerod-download
        with:
          os: linux
          arch: x86_64

      - name: Documentation
        run: ${{ env.CMD_DOC }}

      - name: Clippy (fail on warnings)
        run: ${{ env.CMD_CLIPPY }}

      - name: Test
        run: ${{ env.CMD_TEST }}

      - name: Build
        run: ${{ env.CMD_BUILD }}

      - name: Hack Check
        run: ${{ env.CMD_HACK }}

  # CI, runs in virtual machines.
  ci-vm:
    runs-on: ubuntu-latest

    env:
      CARGO_INCREMENTAL: "0"
      CARGO_PROFILE_DEV_DEBUG: "0"
      CARGO_PROFILE_TEST_DEBUG: "0"
      CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG: "0"

    strategy:
      matrix:
        os: [
          { name: freebsd, architecture: x86_64, version: "15.1", dependencies: "cmake curl git gmake" },
          { name: openbsd, architecture: x86_64, version: "7.9", dependencies: "cmake git gmake rust rust-clippy" },
        ]

    defaults:
      run:
        shell: cpa.sh {0} --sync-files none

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download monerod
        if: matrix.os.name != 'openbsd' # There is no prebuilt monerod for OpenBSD
        uses: ./.github/actions/monerod-download
        with:
          os: ${{ matrix.os.name }}
          arch: ${{ matrix.os.architecture }}

      - name: Start VM
        uses: cross-platform-actions/action@v1.3.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          memory: 6G
          cpu_count: 4
          sync_files: runner-to-vm
          environment_variables: CARGO_TERM_COLOR RUST_BACKTRACE RUST_MIN_STACK RUSTDOCFLAGS CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG CARGO_INCREMENTAL CARGO_PROFILE_DEV_DEBUG CARGO_PROFILE_TEST_DEBUG

      - name: Install dependencies
        run: |
          case "${{ matrix.os.name }}" in
            openbsd)
              sudo pkg_add ${{ matrix.os.dependencies }}
              ;;
            freebsd)
              sudo pkg install -y ${{ matrix.os.dependencies }}
              sudo pkg clean -y
              ;;
          esac

      - name: Install Rust
        if: matrix.os.name == 'freebsd'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --component clippy
          sudo ln -s "$HOME"/.cargo/bin/* /usr/local/bin/

      - name: Documentation
        run: |
          ${{ env.CMD_DOC }}
          cargo clean --doc
          rm -rf "$HOME/.cargo/registry/cache"
          rm -rf "$HOME/.cargo/git/db"

      - name: Clippy (fail on warnings)
        run: ${{ env.CMD_CLIPPY }}

      - name: Test
        run: |
          case "${{ matrix.os.name }}" in
            openbsd)
              ulimit -Sd 4194304
              cargo test --all-features --workspace --exclude cuprate-p2p-core
              cargo test --all-features --package cuprate-p2p-core --lib --tests -- --skip monerod
              ;;
            *)
              ${{ env.CMD_TEST }}
              ;;
          esac

      - name: Build
        run: ${{ env.CMD_BUILD }}

      - name: Hack Check
        run: |
          case "${{ matrix.os.name }}" in
            openbsd)
              cargo install cargo-hack --locked
              cargo hack check --feature-powerset --no-dev-deps --workspace --exclude cuprate-fuzz
              ;;
            *)
              ${{ env.CMD_HACK }}
              ;;
          esac

  # CI, runs cross-compiled targets under emulation.
  ci-cross:
    runs-on: ubuntu-latest

    env:
      PROPTEST_TIMEOUT: 0

    strategy:
      matrix:
        target: [
            riscv64gc-unknown-linux-gnu,
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Install cross toolchain
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ matrix.target }}

      - name: Documentation
        run: ${{ env.CMD_DOC }}

      - name: Clippy (fail on warnings)
        run: ${{ env.CMD_CLIPPY }}

      # There is no prebuilt monerod for RISC-V, so the tests that require it are skipped.
      - name: Test
        run: |
          cargo test --all-features --workspace --exclude cuprate-p2p-core
          cargo test --all-features --package cuprate-p2p-core --lib --tests -- --skip monerod

      - name: Build
        run: ${{ env.CMD_BUILD }}
