name: Hack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hack:

    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ matrix.os }}-hack

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: cargo install cargo-hack --locked
      - name: Hack Check
        # TODO: remove the exclude when `cuprate-blockchain` errors are fixed
        run: argo hack --workspace --exclude cuprate-blockchain  check --feature-powerset --no-dev-deps