name: "Pull Request Labeler"
on:
- pull_request_target

# See .github/labeler.yml file

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
