[package]
name = "cuprate-net"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = {version = "1.0", features =["derive"]}
serde_with = "2.2.0"
epee-serde = {git="https://github.com/Boog900/epee_serde.git"}
monero = "0.18.2"
bitflags = "1.3.2"
byteorder = "1.4.3"
thiserror = "1.0.24"

